### ISSUE TITLE
not reading var_type correctly, all called indels

### ISSUE THREAD

**Issue by amkenney** [jamescasbon/PyVCF#149]
Hello,
I am trying to parse a vcf file I recently made using samtools. My reader thinks all the records are 'indels' even though most are invariant or are snps. When I parse the samtools.vcf example, it works perfectly, so I think it's a problem with my vcf file. (I have previously used GATK to make vcf files and successfully read them using pyvcf. I am new to using samtools to make vcf files, so am still learning the particulars.)

Here are some example record lines from my vcf file. Is the problem that I am missing information in the format field? And no genotype field?
# CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  DUNG

scaffold_1  552 .   G   .   33  .   DP=1;AF1=0;AC1=0;DP4=1,0,0,0;MQ=29;FQ=-30   PL  0
scaffold_1  553 .   T   .   28.2    .   DP=1;;AC1=2;FQ=-30  PL  0
scaffold_1  554 .   C   .   33  .   DP=1;AF1=0;AC1=0;DP4=1,0,0,0;MQ=29;FQ=-30   PL  0
scaffold_1  554 .   CAAAAAAA    .   23.5    .   INDEL;IS=1,1.000000;DP=1;AF1=1;AC1=2;DP4=0,0,1,0;MQ=29;FQ=-37.7 PL  14
scaffold_1  982 .   T   C   76.3    .   DP=5;VDB=1.999423e-02;AF1=1;AC1=2;DP4=0,0,5,0;MQ=37;FQ=-42  PL  109,15,0

Thank you!
Amanda

**Comment by rwness** [comment]
I noticed this error directly in the code when trying to understand the distinctions made between SVs, indels etc. According the the source code currently available on readthedocs. The error is in the "is_indel" function where it says:

    for alt in self.ALT:
                if alt is None:
                    return True

This will means all reference sites are "indels" - you need to change line 392 of model.py ```return False```

**Comment by martijnvermaat** [comment]
Hi @rwness,

I think I agree with your fix, but it breaks some of the unit tests. Could you correct these? You can run them with `python setup.py test`. Thanks!

**Comment by rwness** [comment]
The problem with those unit tests is that site 20:1230237 in the example VCF  [vcf/test/example-4.0.vcf`](vcf/test/example-4.0.vcf/)is not an indel but the tests are designed under the assumption its a deletion:

    20	1230237	.	T	.	47	PASS	NS=3;DP=13;AA=T	GT:GQ:DP:HQ	0|0:54:7:56,60	0|0:48:4:51,51	0/0:61:2

Additionally in the function is_deletion the same logic that I thought was a bug originally exists:

    @property
    def is_deletion(self):
        """ Return whether or not the INDEL is a deletion """
        # if multiple alts, it is unclear if we have a transition
        if len(self.ALT) > 1:
            return False

        if self.is_indel:
            # just one alt allele
            alt_allele = self.ALT[0]
     ### this is where things are going wrong sites with no ALT 
where marked as indels and then marked as deletions even though there was no variation. 
            if alt_allele is None:
                return True
            if len(self.REF) > len(alt_allele):
                return True
            else:
                return False
        else:
            return False

**Comment by martijnvermaat** [comment]
(Sorry, I should've responed in the pull request (#226), but let's continue the discussion here now.)

Since I was a bit puzzled by the issue you found in `is_indel`, I had a look where that code was introduced. That's commit bfbc887, which also introduced the unit tests. I'm quite surprised that this has been in de codebase for so long without anyone raising an issue about it.

Anyway, unless I'm still missing something here, I think your proposed change makes sense. In that case, the tests in `vcf/test/test_vcf.py` should just be updated to expect the correct result.

If this means there are no tests covering (for example) the `is_indel` case anymore, you could add a line for that in the test VCF which should be possible without breaking other tests I think.

Let me know if you if you want to know more.

**Comment by jamescasbon** [comment]
Is #228 ok to go now?

**Comment by rwness** [comment]
As far as I can tell its all good to go. I ran the tests and go no failures and the indel definition makes sense to me now.

**Comment by martijnvermaat** [comment]
Merged #228

**Comment by golharam** [comment]
Has this been pushed to production?  I'm seeing this is PyVCF==0.6.8, which just got installed via 'pip install pyvcf'
