### ISSUE TITLE
Report PASS filter instead of removing it

### ISSUE THREAD

**Issue by ihodes** [jamescasbon/PyVCF#153]
If the FILTER column of a record in VCF is "PASS", instead of reporting that in the _Record as `['PASS']`, PyVCF instead reports an empty array, `[]`. 

As far as I or grep could tell, this isn't documented and it isn't clear that this is happening without reading the source. As `[]` is treated as a falsey value in Python, I'm not sure it makes sense semantically. 

I'd be happy to submit a PR to change this if desired, but if a change shouldn't be made, I'm curious as to the reasoning behind this? 

---

in parser.py:550-555:

``` python
if filt == '.':
    filt = None
elif filt == 'PASS':
    filt = []
else:
    filt = filt.split(';')
```

**Comment by mh00h** [comment]
Did this ever get pushed into documentation? I had to search for this thread as well.
