### ISSUE TITLE
Fetch not finding correct file. 

### ISSUE THREAD

**Issue by nathansharris** [jamescasbon/PyVCF#167]
Cannot get fetch to work as expected. I am looking at data from the 1000 genomes. The minimal code that reproduces the error is:

vcf_reader = vcf.Reader(open("ALL.chr3.phase1_release_v3.20101123.snps_indels_svs.genotypes.vcf.gz"))

vcf_reader.fetch('3',1,2)

And the following error:

/usr/local/lib/python2.7/dist-packages/vcf/parser.pyc in fetch(self, chrom, start, end)
    582 
    583         if not self._tabix:
--> 584             self._tabix = pysam.Tabixfile(self.filename)
    585 
    586         if self._prepend_chr and chrom[:3] == 'chr':

/usr/local/lib/python2.7/dist-packages/pysam/ctabix.so in pysam.ctabix.Tabixfile.**cinit** (pysam/ctabix.c:2547)()

/usr/local/lib/python2.7/dist-packages/pysam/ctabix.so in pysam.ctabix.Tabixfile._open (pysam/ctabix.c:3052)()

IOError: index `ALL.chr3.phase1_release_v3.20101123.snps_indels_svs.genotypes.vcf.gz.tbi` not found

Am I missing something obvious? Thanks.

**Comment by zheng-liu** [comment]
I ran the fetch function and got the following error too. Seems the pysam needs files in "*.vcf.tbi" format, while I only have "*.vcf.gz.tbi" files.

>>> `vcf_reader.fetch('2', 10, 20)`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zl/anaconda2/lib/python2.7/site-packages/vcf/parser.py", line 626, in fetch
    encoding=self.encoding)
  File "pysam/ctabix.pyx", line 302, in pysam.ctabix.TabixFile.__cinit__ (pysam/ctabix.c:3455)
  File "pysam/ctabix.pyx", line 331, in pysam.ctabix.TabixFile._open (pysam/ctabix.c:3902)
IOError: index `ALL.chr2.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.tbi` not found

**Comment by martijnvermaat** [comment]
I don't think this is correct. Are you sure you are reading the `.vcf.gz` file and not the `.vcf` file?
