### ISSUE TITLE
VDB Error

### ISSUE THREAD

**Issue by danielecook** [jamescasbon/PyVCF#169]
The vcfs from the new version of bcftools can't be read.

 bcftools view test2.bcf | vcf_melt

Traceback (most recent call last):
  File "/usr/local/bin/vcf_melt", line 19, in <module>
    reader = vcf.VCFReader(inp)
  File "/usr/local/lib/python2.7/site-packages/vcf/parser.py", line 288, in __init__
    self._parse_metainfo()
  File "/usr/local/lib/python2.7/site-packages/vcf/parser.py", line 309, in _parse_metainfo
    key, val = parser.read_info(line)
  File "/usr/local/lib/python2.7/site-packages/vcf/parser.py", line 123, in read_info
    "One of the INFO lines is malformed: %s" % info_string)
SyntaxError: One of the INFO lines is malformed: ##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version=3>

**Comment by johanneskoester** [comment]
Here comes the full error message. The VDB entry is correct according to the Spec.

```
One of the INFO lines is malformed: ##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">
```

I am pretty sure that the Version tag is causing the issue here. Does PyVCF only support vcf 4.1?

**Comment by danielecook** [comment]
It doesn't but modified it in [this fork](https://github.com/danielecook/PyVCF) to use bcftools under the hood. If you are on a unix based system it should work.

**Comment by johanneskoester** [comment]
Thanks. Actually I discovered that it works now with current git master. I had the newest PyPi version previously.

**Comment by danielecook** [comment]
Ok great! I think we can close this issue then.
