### ISSUE TITLE
VCFv4.2 compatibility...

### ISSUE THREAD

**Issue by travc** [jamescasbon/PyVCF#172]
**Edit by** @martijnvermaat: Let's have this as the main issue for tracking VCFv4.2 compatibility.

I think the following are all changes from VCFv4.1 to VCFv4.2. (That's not to say that our VCFv4.1 support is complete of course.)
- [x] Add `R` as an _INFO_ field count (number of alleles including reference).
- [x] Support the optional _Source_ and _Version_ keys on _INFO_ metainformation.
- [ ] Support any number of extra fields after the default ones in _INFO_, _FORMAT_, _FILTER_, and _ALT_ metainformation. These optional fields should always be stored as strings.
- [ ] Handle `*` as _ALT_ value (reserved to indicate that the allele is missing due to an upstream deletion). Not sure what to do with it, if anything.

---

The new samtools/bcftools/htslib are producing VCFv4.2, which is causing PyVCF problems.
I've made some changes to header parsing which gets it to work on my files, but I seriously doubt this is a complete fix.  Here is the diff...

``` diff
diff --git a/vcf/parser.py b/vcf/parser.py
index 9e4f739..e055a3b 100644
--- a/vcf/parser.py
+++ b/vcf/parser.py
@@ -63,8 +63,9 @@ SINGULAR_METADATA = ['fileformat', 'fileDate', 'reference']
 # Conversion between value in file and Python value
 field_counts = {
     '.': None,  # Unknown number of values
-    'A': -1,  # Equal to the number of alleles in a given record
+    'A': -1,  # Equal to the number of alternate alleles in a given record
     'G': -2,  # Equal to the number of genotypes in a given record
+    'R': -3,  # Equal to the number of alleles including reference in a given record
 }


@@ -82,9 +83,11 @@ class _vcf_metadata_parser(object):
         super(_vcf_metadata_parser, self).__init__()
         self.info_pattern = re.compile(r'''\#\#INFO=<
             ID=(?P<id>[^,]+),
-            Number=(?P<number>-?\d+|\.|[AG]),
+            Number=(?P<number>-?\d+|\.|[AGR]),
             Type=(?P<type>Integer|Float|Flag|Character|String),
             Description="(?P<desc>[^"]*)"
+            (?:,Source="(?P<source>[^"]*)"){0,1}
+            (?:,Version=(?P<version>[^"]*)){0,1}
             >''', re.VERBOSE)
         self.filter_pattern = re.compile(r'''\#\#FILTER=<
             ID=(?P<id>[^,]+),
@@ -96,7 +99,7 @@ class _vcf_metadata_parser(object):
             >''', re.VERBOSE)
         self.format_pattern = re.compile(r'''\#\#FORMAT=<
             ID=(?P<id>.+),
-            Number=(?P<number>-?\d+|\.|[AG]),
+            Number=(?P<number>-?\d+|\.|[AGR]),
             Type=(?P<type>.+),
             Description="(?P<desc>.*)"
             >''', re.VERBOSE)
```

PS: I really like PyVCF...  Makes life much easier.  Thanks.

**Comment by kotoroshinoto** [comment]
how do we go about grabbing and digesting the extra fields?
