### ISSUE TITLE
Retrieve header info?

### ISSUE THREAD

**Issue by ronammar** [jamescasbon/PyVCF#197]
Is there a way to retrieve header info that corresponds to the record attributes in the INFO field?

**Comment by martijnvermaat** [comment]
I'm not sure if I understand you correctly, but say you have an INFO field `NS` in a record (`record.INFO['NS']`), you are interested in the definition of `NS` as presented in the VCF header?

Then, yes, you can do something like this:

    >>> reader = vcf.Reader(filename='test.vcf')
    >>> reader.infos['NS']
    Info(id='NS', num=1, type='Integer', desc='Number of Samples With Data', source=None, version=None)
    >>> reader.infos['NS'].num
    1

Please reopen this issue if that doesn't solve your problem.

**Comment by esthercamilo** [comment]
I think you didn't understand. In the header we have the meaning of each info. How to retrieve those meanings. They are comments though.
