### ISSUE TITLE
disabling decompression being force on

### ISSUE THREAD

**Issue by cariaso** [jamescasbon/PyVCF#198]
for my use case
fh is a gzip object, so I'm doing my decompression outside of the reader. I'd hoped

vcf.Reader(fsock=fh, compressed=False)

would solve this, but 
https://github.com/jamescasbon/PyVCF/blob/master/vcf/parser.py
line 259 is written in a way, that the .gz suffix forces compression on, even though it was explicitly passed as False. consider changing the default function param to
compressed=None
and changing lines 259 and 261 to something like
if compressed is None: compressed = filename.endswith('.gz')

without this it is necessary to lie about the original filename via a
fh.name = 'fakename'

**Comment by martijnvermaat** [comment]
I think your proposed fix is sound, would you care to submit a pull request?
