### ISSUE TITLE
unable to parse

### ISSUE THREAD

**Issue by cariaso** [jamescasbon/PyVCF#202]
ftp://ftp.ebi.ac.uk/pub/databases/eva/PRJEB8636/ERZ108620/decode_variants_chr22.EVA.fixed.vcf.gz
and all of the other genomes from
http://www.nature.com/articles/sdata201511
https://www.ebi.ac.uk/eva/?eva-study=PRJEB8636
with the message

    vcf_reader = vcf.Reader(fsock=vcffh, compressed=False)
  File "/Library/Python/2.7/site-packages/vcf/parser.py", line 288, in __init__
    self._parse_metainfo()
  File "/Library/Python/2.7/site-packages/vcf/parser.py", line 325, in _parse_metainfo
    key, val = parser.read_contig(line)
  File "/Library/Python/2.7/site-packages/vcf/parser.py", line 173, in read_contig
    "One of the contig lines is malformed: %s" % contig_string)
SyntaxError: One of the contig lines is malformed: ##contig=<ID=1,accession=NC_000001.9,assembly=GCF_000001405.12>

**Comment by mattions** [comment]
Latest master can parse this, so if you get that you should be OK.

I'm wondering when a new release will be rolled out, given the fact 0.6.7
now is quite old compared to the current master.

**Comment by cariaso** [comment]
Thanks. I will close this issue, but strongly agree with the need for a new release since my own commit is the last one accepted, and I'd like to be able to use that via a pip install.
