### ISSUE TITLE
Comma Delimited RS id fields not being parsed from source VCF 

### ISSUE THREAD

**Issue by GlyphDataServices** [jamescasbon/PyVCF#205]
Hi all,
I'm working with pyVCF on some annotated variants, and noticed that comma separated dbSNP rs ids are not parsed.  Only the first id seems to be parsed and subsequent ids are discarded.

Any fix for this in the pipeline? I was thinking of tweaking the parser to accommodate. 

For example my input vcf INFO has:
RS=3131949,71507463;RSPOS=827221,827221;...

but one of the rs ids is skipped when parsed:
'RS': 3131949, ...

**Comment by martijnvermaat** [comment]
This should work correctly if the field was described in an `INFO` header with `Number=.`, for example:

    ##INFO=<ID=RS,Number=.,Type=Integer,Description="dbSNP rs ids">

Please reopen if this doesn't help you.
