### ISSUE TITLE
Is the python 3 branch far behind master?

### ISSUE THREAD

**Issue by WimS83** [jamescasbon/PyVCF#208]
Hi thanks for this great VCF parser! 

I am wondering if the Python3 branch is far behind the master branch?
https://github.com/jamescasbon/PyVCF/tree/master
https://github.com/jamescasbon/PyVCF/tree/python3

I have installed pyvcf using pip3.4 which somehow installed the correct python3 branch. Or is there a forked pyvcf python3 project somewhere else? 

So far all functionality that is need is available (after you find out that you have to call  2underscores next 2underscores instead of next on the vcf reader. :) )

If the python3 branch is to far behind I might have to downgrade to using python2. Or maybe somebody could port the more recent commits to the python3 branch?

**Comment by martijnvermaat** [comment]
Sorry Wim, I missed this issue. To reiterate from my email for other interested parties:

The current master branch should work on Python 3, as can be seen [on Travis CI](https://travis-ci.org/jamescasbon/PyVCF).

But if you have any problems, patches are always welcome.

By the way, `record = next(reader)` should also work ;)
