### ISSUE TITLE
One of the INFO lines is malformed

### ISSUE THREAD

**Issue by VidJa** [jamescasbon/PyVCF#213]
I get the following error on a vcf file generated with a recent samtools/bcftools combo

"One of the INFO lines is malformed: %s" % info_string)
SyntaxError: One of the INFO lines is malformed: ##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">

The "Version="3" part at the end of the INFO line is causing the error.

**Comment by martijnvermaat** [comment]
Could you share the complete INFO line that is causing the error?

**Comment by VidJa** [comment]
oops, truncated paste.

##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">

This comes from a simple bowtie2 --> samtools --> bcftools combo (samtools-1.2 htslib-1.2.1)
samtools mpileup -u -f <ref> <bam>  | bcftools call -mv -Oz -o calls.vcf.gz

**Comment by martijnvermaat** [comment]
Ah, didn't see that, thanks.

This seems to be the same issue as #169. I'm not sure when exactly, but it has been fixed in master.

To use master, you can do:

    pip install -e git+https://github.com/jamescasbon/PyVCF.git#egg=PyVCF
