### ISSUE TITLE
is_snp doesn't allow spanning deletions

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [jamescasbon/PyVCF#214]
When a snip occurs that contains a spanning deletion ( see http://gatkforums.broadinstitute.org/discussion/5647/new-allele-and-the-vcf-file-format) as one of the calls, PyVCF doesn't classify it as a snip (via record.is_snp).

> print(s)
Record(ref, POS=456904, REF=T, ALT=[C, *])
> s.is_snp
False

Using gatk's own VariantsToTable walker with -F TYPE does classify it as a snip.

**Comment by martijnvermaat** [comment]
Fixed with #215
