### ISSUE TITLE
AttributeError: 'Reader' object has no attribute 'next'

### ISSUE THREAD

**Issue by krlk89** [jamescasbon/PyVCF#218]
I'm using Python 3.4.3 and I've tried both PyVCF 0.6.7 and 0.6.8-dev. My code looks as follows:
```
import vcf

vcf = vcf.Reader(open("test.vcf", "r"))
record = vcf.next()
print(record)
```
And after executing the script I get the following error:
```
Traceback (most recent call last):
  File ".\vcf_test.py", line 47, in <module>
    mask_seq()
  File ".\vcf_test.py", line 15, in mask_seq
    record = vcf.next()
AttributeError: 'Reader' object has no attribute 'next'
```

Iterating over vcf using a for cycle works just fine:
```
import vcf

vcf = vcf.Reader(open("test.vcf", "r"))
for record in vcf:
    print(record)
```

**Comment by martijnvermaat** [comment]
In Python 3, use the [next](https://docs.python.org/3/library/functions.html#next) function for this:

    record = next(vcf)

Feel free to re-open this ticket if there's still a problem.

**Comment by krlk89** [comment]
@martijnvermaat Thank you for your help, I guess it would be good to update the documentation to avoid that kind of silly problems. I could try to help out if it's ok.

**Comment by martijnvermaat** [comment]
I didn't realize the old way was in the docs. If you want to change it,
please go ahead. We support Python 2.6 and up, which all have the `next`
built-in, so you can probably just replace it.

**Comment by wheaton5** [comment]
Python 2 is depricated. Can the docs be updated for python3? I just spent about an hour figuring this out.
