### ISSUE TITLE
SNPs and indels merged into a single record

### ISSUE THREAD

**Issue by krlk89** [jamescasbon/PyVCF#224]
VCF specification allows SNPSs and indels to be merged into a single record.

For example:
```
Ref: a t C g a // C is the reference base
   : a t G g a // C base is a G in some individuals (SNP)
   : a t C A g a // A base is inserted (indel)

Corresponding (simplified) VCF record would look something like this:
20     2 .         C      G,CA
```
However, in the described case, record.var_type returns always "indel". Is it possible to differentiate the types of alternative alleles in such cases?

**Comment by martijnvermaat** [comment]
The `var_type` property is on the record level, so it tries to give you a most general type for the entire record.

The variant alleles themselves come with a `type` property which you might find useful:

```python
>>> print r
Record(CHROM=troy, POS=21, REF=A, ALT=[G, AG])
>>> r.var_type
'indel'
>>> r.ALT[0].type
'SNV'
>>> r.ALT[1].type
'MNV'
```
