### ISSUE TITLE
VEP CSQ fields can contain `=` which breaks parsing

### ISSUE THREAD

**Issue by dakl** [jamescasbon/PyVCF#225]
The following variant line

```
1       115251195       .       C       G       .       .       AC=2;AF=0.25;AN=8;set=variant17;CSQ=G|ENSG00000213281|ENST00000369535|Transcript|synonymous_variant|785/4449|531/570|177/189|G|ggG/ggC||||1|NM_002524.4|5/7|||||||-1||YES|NRAS|HGNC||||protein_coding|ENSP00000358548||CCDS877.1|ENST00000369535.4:c.531N>C|ENST00000369535.4:c.531N>C(p.=)|||||        GT      ./.     ./.     ./.     ./.     ./.
```

silently causes an error when reading with pyvcf, due to the `=` in the string (element `ENST00000369535.4:c.531N>C(p.=)` towards the end of the string. Currently, no error is thrown, and pyvcf truncates the string to `G|ENSG00000213281|ENST00000369535|Transcript|synonymous_variant|785/4449|531/570|177/189|G|ggG/ggC||||1|NM_002524.4|5/7|||||||-1||YES|NRAS|HGNC||||protein_coding|ENSP00000358548||CCDS877.1|ENST00000369535.4:c.531N>C|ENST00000369535.4:c.531N>C(p.`. 

Is there anyway that `=` can be escaped by pyvcf? One could for example have a dedicated parser of the CSQ field if present.

Is there any workaround that I'm missing? 

thanks

**Comment by martijnvermaat** [comment]
Hi @dakl , thanks for the report!

I believe this is the same issue as #181 which has been fixed. Unfortunately that fix is not in the latest PyVCF release yet, so you need to use the development version for that. One way to install the latest development version is:

    pip install -e git+https://github.com/jamescasbon/PyVCF.git#egg=PyVCF

Let me know if you need help with that or this doesn't solve your problem.

**Comment by dakl** [comment]
Yes, indees it looks like it's the same issue. Any idea when this fix will reach a release?

**Comment by martijnvermaat** [comment]
I'm sorry, but [this comment](https://github.com/jamescasbon/PyVCF/issues/200#issuecomment-103680432) is still where we are at the moment.
