### ISSUE TITLE
Can we have a 0.6.8 release?

### ISSUE THREAD

**Issue by holtgrewe** [jamescasbon/PyVCF#229]
The previous release is already quite old and the master branch contains important fixes (such as contig lines being valid despite having no length).

**Comment by johanneskoester** [comment]
+1 :-)

**Comment by LeeTL1220** [comment]
+1 Especially if VCF 4.2 can be read properly (0.6.7 is failing on ``##INFO .... Number=R... ``)

**Comment by jamescasbon** [comment]
Ask and ye shall receive https://pypi.python.org/pypi/PyVCF/0.6.8

Please let me know if you have problems.  

Is there some magic command I should be using to build and upload wheels now?

**Comment by martijnvermaat** [comment]
Not sure what the current best practices are. It's uncommon to upload Linux wheels (I think there are still issues related to differences between libc versions), but I see OSX and Windows wheels pretty often.
