### ISSUE TITLE
Error when try read vcf file

### ISSUE THREAD

**Issue by andrelramos** [jamescasbon/PyVCF#237]
This is my VCF file:
```
BEGIN:VCARD
VERSION:2.1
EMAIL;PREF:pastorcjunior@hotmail.com
END:VCARD
```

This is my code:
```
>>> a = open('/home/marco/contacts2.vcf','r')
>>> r = vcf.Reader(a)
>>> next(r)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/saapenv/lib/python3.5/site-packages/vcf/parser.py", line 547, in __next__
    pos = int(row[1])
IndexError: list index out of range
>>> 
```

 Can someone help me?

**Comment by koalive** [comment]
Hello,

Sorry but this is not the same type of VCF file. This library is for the variant calling format, and not the electronic business card format, which have nothing in common, except the file extension !

Have a great day.

**Comment by andrelramos** [comment]
@koalive Thank you fpr your answard.

If someone has the same problem, i found it the VObject project. Is helping me :smile:
