### ISSUE TITLE
Error when creating empty records with `make_calldata_tuple` and `_Call`

### ISSUE THREAD

**Issue by bow** [jamescasbon/PyVCF#243]
Hello PyVCF developers,

Some time ago I needed to write a VCF merging script that involves creating empty sample calls (for when a call at a given position is present in one sample but not the other). This involves the use of `vcf.model.make_calldata_tuple`.

The way I created the empty record was to simply get the expected `FORMAT` keys and use them like this:

```
empty_call_func = make_calldata_tuple(format_keys)
empty_call = _Call(None, sample_name, empty_call_func(*[None for n in format_keys]))
```

This worked when I was doing it on PyVCF 0.6.7. However in the most recent release (0.6.8), I stumbled on this error:

```
Traceback (most recent call last):
  File "/exports/test/vcf_merge.py", line 51, in <module>
    empty_call = _Call(None, sample, empty_cd_func(*[None for n in writer.template.formats]))
  File "/usr/local/sasc/miniconda3/envs/test/lib/python3.5/site-packages/vcf/model.py", line 27, in __init__
    self.gt_alleles = [(al if al != '.' else None) for al in allele_delimiter.split(self.data.GT)]
TypeError: expected string or bytes-like object
```

Upon checking it further, it seems the culprit was [this particular line](https://github.com/jamescasbon/PyVCF/blob/master/vcf/model.py#L26). It's not very apparent, but the check there is only for whether the attribute (which may well be `None`) is present or not. I think a more thorough check should be:

```
if hasattr(self.data, 'GT') and self.data.GT is not None:
```

There is also an additional error that assumes implicit conversion of `True` to an  `int` [here](https://github.com/jamescasbon/PyVCF/blob/master/vcf/model.py#L282). There, it seems that the better call should be:

```
return sum(1 for s in self.samples if s.called)
```

So that even when `s.called` is None, it will still work.

Now, I'm not exactly sure first if the way I created the empty record is the best (I used `_Call`, which I know is supposed to be private). So I'm open to suggestions of doing another way :). Still, I do think the previous two lines can be improved so that they're more error-resistant.

(by the way, these are only two simple code change so I thought I'd just open an issue here. Let me know if you prefer otherwise).

Thanks in advance for looking into this :).

**Comment by martijnvermaat** [comment]
Hey @bow :)

I'm not sure if there would be a better way to do this at the moment, editing/writing support is quite incomplete and it needs a bit of hacking around and using private interfaces.

I agree with both of your suggestions, if you could create a PR for them I'd merge it.

Your first suggestion can be shortened to:
```python
if getattr(self.data, 'GT', None) is not None:
```

**Comment by bow** [comment]
Hey @martijnvermaat :),

Ok then, I've just pushed the branch (with your suggestion as well). It should be visible soon.

Thanks!
