### ISSUE TITLE
Genotype level filters not supported

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [jamescasbon/PyVCF#246]
Next to the normal FILTER, vcf files can also contain per-genotype filters, using the FT annotation in the FORMAT field. The format mimics the formatting of the FILTER field, eg 'PASS' for passing the filter, and 'filt1;filt2' for failing two filters.

From the VCFv4.2 spec:

> FT : sample genotype filter indicating if this genotype was “called” (similar in concept to the FILTER field). Again, use PASS to indicate that all filters have been passed, a semi-colon separated list of codes for filters that fail, or ‘.’ to indicate that filters have not been applied. These values should be described in the meta-information in the same way as FILTERs (String, no white-space or semi-colons permitted)

For now, PyVCF treats the FT annotation as a regular annotation instead of as a filter. I would like to add support for the FT annotation, and will post a pull request when I have a working implementation.

**Comment by martijnvermaat** [comment]
Implemented in #247
