### ISSUE TITLE
Use a consistent data type for fields with a given format?

### ISSUE THREAD

**Issue by sambrightman** [jamescasbon/PyVCF#254]
These lines:

```
                # we don't need to split single entries
                 if entry_num == 1 or ',' not in vals:
```

in `parser.py` do not seem ideal. The first part of the condition – if the type of the field is `Number=1` – makes complete sense: do not provide a list for something that is always length 1. But the second part seems inconsistent when `Number` > 1, or `R`/`A` etc. A list is provided at one position and a non-list at another position because of the incidental difference in calls. It also makes it harder to deal with from client code - you can't only know the format of the field you are interested in. Is there a strong reason to do this?

**Comment by sambrightman** [comment]
I can of course submit a PR for this but it's not clear to me if the project is still alive.

**Comment by martijnvermaat** [comment]
I can only speak for myself, but my time for PyVCF is very limited since I'm currently not working in bioinformatics. That said, I'm more than happy to have a look at PRs if they come with a clear description and tests and don't take too much time to review.

In this specific case, a minimal example of a file that's parsed in an unexpected would be helpful. From a quick look at the code, I think [line 507](https://github.com/jamescasbon/PyVCF/blob/master/vcf/parser.py#L507) just following the one you cite does not work as intended: `sampdat[i] = (sampdat[i])` (it needs a comma to create a singleton tuple or square brackets to create a singleton list).

**Comment by sambrightman** [comment]
Ok. I saw, for example, #228 not being merged and no release for a while. Is there anyway to help existing fixes get merged and released?

I've submitted #259 as a first attempt at this one.

**Comment by martijnvermaat** [comment]
I merged #228. Generalizing a bit, I think existing unmerged pull requests are either waiting for submitter feedback, take too much time to properly review, or just need more discussion/thinking whether they should be merged at all.

So I think reviewing PRs, commenting on their pros, cons, or suggesting they should not be merged would definitely help. Anything that would get the PR in shape for a merge, or help make a decision to not include it.

**Comment by martijnvermaat** [comment]
@sambrightman Since you seem interested in the project and have contributed some useful work lately, would you be interested in push access?

@jamescasbon See #259 #260 #263

**Comment by sambrightman** [comment]
Yes, although I'm very likely to be another part-time contributor in the near future. I'd like to see PyVCF in a tested/releasable state so we feel comfortable adding a dependency on it, hopefully get a new release out with current known fixes. Also looking a little at performance, since it is rather slow for us even with Cython. After that I can probably only manage occasional review in my free time. Likely to still be worth having so it's easier to tidy up PRs or add occasional tests etc.

**Comment by sambrightman** [comment]
One case where this is not backwards-compatible is if running on a VCF that is normalised to a single alt per line (or using a caller that only ever outputs a single allele). In this case client code could depend on not indexing into a field that should be a list, and will now have to do so.
