### ISSUE TITLE
no attribute 'data' in dict: sample.data

### ISSUE THREAD

**Issue by mh00h** [jamescasbon/PyVCF#265]
https://github.com/jamescasbon/PyVCF/blob/master/vcf/parser.py#L744

    def _format_sample(self, fmt, sample):
        if hasattr(sample.data, 'GT'):
        
        AttributeError: 'dict' object has no attribute 'data'

Seems the writer is missing some type safety, making the writer unusable.

**Comment by martijnvermaat** [comment]
That's very well possible, the writer is quite incomplete. Can you give a minimal example triggering this exception?

**Comment by mh00h** [comment]
Hi- heartbeat to say I am still aware of this issue that was filed. Ran out of time and working around the issue for now. I'll bring an example here as soon as I can. Thanks for your patience!

**Comment by mh00h** [comment]
I don't have an example to provide at this time so closing this bug.
