### ISSUE TITLE
Installation error error: can't copy 'vcf/cparse.c': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by wcardoen** [jamescasbon/PyVCF#279]
Hello,

I used python 2.7.11 (Centos 7 OS) and the pyVCF 0.6.8 source code:
python setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/vcf
copying vcf/utils.py -> build/lib.linux-x86_64-2.7/vcf
copying vcf/parser.py -> build/lib.linux-x86_64-2.7/vcf
copying vcf/__init__.py -> build/lib.linux-x86_64-2.7/vcf
copying vcf/filters.py -> build/lib.linux-x86_64-2.7/vcf
copying vcf/sample_filter.py -> build/lib.linux-x86_64-2.7/vcf
copying vcf/model.py -> build/lib.linux-x86_64-2.7/vcf
creating build/lib.linux-x86_64-2.7/vcf/test
copying vcf/test/test_vcf.py -> build/lib.linux-x86_64-2.7/vcf/test
copying vcf/test/__init__.py -> build/lib.linux-x86_64-2.7/vcf/test
copying vcf/test/prof.py -> build/lib.linux-x86_64-2.7/vcf/test
running egg_info
writing requirements to PyVCF.egg-info/requires.txt
writing PyVCF.egg-info/PKG-INFO
writing top-level names to PyVCF.egg-info/top_level.txt
writing dependency_links to PyVCF.egg-info/dependency_links.txt
writing entry points to PyVCF.egg-info/entry_points.txt
reading manifest file 'PyVCF.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'PyVCF.egg-info/SOURCES.txt'
error: can't copy 'vcf/cparse.c': doesn't exist or not a regular file

Thanks,

Wim

**Comment by guillermomarco** [comment]
I'm having the same issue, tried upgrading to `setuptools-39.2.0` without luck.
