### ISSUE TITLE
Problem reading vcf file.

### ISSUE THREAD

**Issue by CanadianGPD** [jamescasbon/PyVCF#71]
Hi 

I'm having trouble reading my vcf file with PyVCF.    Any help would be useful the file I'm trying to read was created by vcf tools.

Here is the code:

import vcf
vcf_reader = vcf.Reader(open('all.mergedSNPs.vcf','r'))
for rec in vcf_reader:
    print rec

But I get this error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/PyVCF-0.6.0-py2.7-macosx-10.7-intel.egg/vcf/parser.py", line 443, in next
    pos = int(row[1])
IndexError: list index out of range

**Comment by etowahs** [comment]
I got this error and was able to resolve it by removing the trailing new line in my vcf file as @jamescasbon suggested. Thanks.
